test: Use list-partitions to validate delete-partition test
Also reduce number of rows in tripdata.parquet test file.

diff --git a/ice-rest-catalog/src/test/resources/scenarios/delete-partition/run.sh.tmpl b/ice-rest-catalog/src/test/resources/scenarios/delete-partition/run.sh.tmpl
--- a/ice-rest-catalog/src/test/resources/scenarios/delete-partition/run.sh.tmpl
+++ b/ice-rest-catalog/src/test/resources/scenarios/delete-partition/run.sh.tmpl
@@ -15,17 +15,18 @@ INPUT_PATH="${SCENARIO_DIR}/${INPUT_FILE}"
 {{ICE_CLI}} --config {{CLI_CONFIG}} insert --create-table ${TABLE_NAME} ${INPUT_PATH} --partition="${PARTITION_SPEC}"
 echo "OK Inserted data with partitioning into table ${TABLE_NAME}"
 
-# Delete partition for a specific day
-output=$({{ICE_CLI}} --config {{CLI_CONFIG}} delete ${TABLE_NAME} --partition "[{\"name\": \"${TRANSFORMED_PARTITION_COLUMN}\", \"values\": [\"${DELETE_PARTITION_DAY}\"]}]" 2>&1)
-
-echo "$output"
-
-line_count=$(echo "$output" | wc -l)
-
-if [ "$line_count" -ne 1 ]; then
-  echo "FAIL Expected 1 line, got $line_count"
+# Validate partition exists before deletion
+list_before=$({{ICE_CLI}} --config {{CLI_CONFIG}} list-partitions ${TABLE_NAME})
+if [[ "$list_before" != *"${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY}"* ]]; then
+  echo "FAIL Expected partition key ${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY} in list-partitions before delete"
   exit 1
 fi
+echo "OK Partition exists before deletion"
+
+# Delete partition for a specific day
+output=$({{ICE_CLI}} --config {{CLI_CONFIG}} delete ${TABLE_NAME} --dry-run=false --partition "[{\"name\": \"${TRANSFORMED_PARTITION_COLUMN}\", \"values\": [\"${DELETE_PARTITION_DAY}\"]}]" 2>&1)
+
+echo "$output"
 
 if ! echo "$output" | grep -qF "${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY}"; then
   echo "FAIL Expected output to contain '${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY}'"
@@ -33,6 +34,14 @@ if ! echo "$output" | grep -qF "${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITI
 fi
 
 echo "OK Deleted partition with value ${DELETE_PARTITION_DAY}"
+
+# Validate partition was deleted
+list_after=$({{ICE_CLI}} --config {{CLI_CONFIG}} list-partitions ${TABLE_NAME})
+if [[ "$list_after" == *"${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY}"* ]]; then
+  echo "FAIL Deleted partition key ${TRANSFORMED_PARTITION_COLUMN}=${DELETE_PARTITION_DAY} in list-partitions after delete"
+  exit 1
+fi
+echo "OK Validated partition was deleted"
 
 # Cleanup
 {{ICE_CLI}} --config {{CLI_CONFIG}} delete-table ${TABLE_NAME}
